use project;

#Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue 
from cleaned_customer_shopping_behavior
group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select  customer_id, purchase_amount
from cleaned_customer_shopping_behavior
where discount_applied ='yes' and purchase_amount >=(select avg(purchase_amount) from cleaned_customer_shopping_behavior);

 #Q3. Which are the top 5 products with the highest average review rating? 
 select item_purchased,round(avg(review_rating),2) as "Average Product Rating"
 from cleaned_customer_shopping_behavior
 group by item_purchased
 order by round(avg(review_rating),2)  desc
 limit 5;
 
 #Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select avg(purchase_amount),shipping_type
from cleaned_customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;

#Q5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
 select subscription_status,sum(purchase_amount) as 'Total Revenue',avg(purchase_amount) as 'Avarage Spend'
 from cleaned_customer_shopping_behavior
 group by subscription_status;
 
#Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM cleaned_customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as
(
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 Then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_sagement
from cleaned_customer_shopping_behavior    
)
select  customer_sagement, count(*) as 'Number of Customers'
from customer_type
group by customer_sagement;

# What are the top 3 most purchased products within each category? 
with item_count as
(
select category,item_purchased,
count(customer_id) as 'total_orders',
row_number() over (partition by category order by count(customer_id)desc) as 'item_rank'
from cleaned_customer_shopping_behavior
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders 
from item_count
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from cleaned_customer_shopping_behavior
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?  
select sum(purchase_amount),age_group
from cleaned_customer_shopping_behavior
group by age_group
order by sum(purchase_amount) desc;